/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115162-gd7924a4f60-20240510"
#endif /* AVUTIL_FFVERSION_H */
